SELECT * FROM CARRITO_PRODUCTOS;


SELECT * FROM CARRITOS;

SELECT DP.ID_DETALLE,
       CP.ID_CARRITO,
       P.NOMBRE||' - '|| P.MARCA AS PRODUCTO,
       CP.CANTIDAD,
       DP.DIRECCION
FROM DETALLE_PEDIDO DP JOIN CARRITO_PRODUCTOS CP ON DP.ID_CARRITO = CP.ID_CARRITO JOIN PRODUCTOS P ON CP.ID_PRODUCTO = P.ID_PRODUCTO;

SELECT * FROM PRODUCTOS;

SELECT  I.ID_INVENTARIO,
        S.NOMBRE AS SUCURSAL,
        P.NOMBRE||' - '|| P.MARCA AS PRODUCTO,
        I.STOCK
FROM INVENTARIO I JOIN PRODUCTOS P ON I.ID_PRODUCTO = P.ID_PRODUCTO JOIN SUCURSALES S ON I.ID_SUCURSAL = S.ID_SUCURSAL;

select * from DETALLE_PEDIDO;

SELECT * FROM usuarios;


SELECT * FROM SUCURSALES;
