SELECT * FROM CARRITO_PRODUCTOS;

SELECT * FROM CARRITOS;

SELECT DP.ID_DETALLE,
       CP.ID_CARRITO,
       P.NOMBRE||' - '|| P.MARCA AS PRODUCTO,
       CP.CANTIDAD,
       DP.DIRECCION
FROM DETALLE_PEDIDO DP JOIN CARRITO_PRODUCTOS CP ON DP.ID_CARRITO = CP.ID_CARRITO JOIN PRODUCTOS P ON CP.ID_PRODUCTO = P.ID_PRODUCTO;

SELECT * FROM PRODUCTOS;

