-- Script para verificar y limpiar carritos problemáticos

-- Verificar carritos existentes
SELECT 'CARRITOS EXISTENTES:' as info;
SELECT ID_CARRITO, FECHA_CREACION FROM CARRITOS ORDER BY ID_CARRITO;

-- Verificar productos en carritos
SELECT 'PRODUCTOS EN CARRITOS:' as info;
SELECT ID_CARRITO, COUNT(*) as productos FROM CARRITO_PRODUCTOS GROUP BY ID_CARRITO ORDER BY ID_CARRITO;

-- Limpiar carritos que no existen en la tabla CARRITOS
DELETE FROM CARRITO_PRODUCTOS 
WHERE ID_CARRITO NOT IN (SELECT ID_CARRITO FROM CARRITOS);

-- Verificar carritos huérfanos (sin productos)
SELECT 'CARRITOS SIN PRODUCTOS:' as info;
SELECT c.ID_CARRITO, c.FECHA_CREACION 
FROM CARRITOS c 
LEFT JOIN CARRITO_PRODUCTOS cp ON c.ID_CARRITO = cp.ID_CARRITO 
WHERE cp.ID_CARRITO IS NULL;

-- Opcional: Eliminar carritos vacíos
-- DELETE FROM CARRITOS 
-- WHERE ID_CARRITO NOT IN (SELECT DISTINCT ID_CARRITO FROM CARRITO_PRODUCTOS);

COMMIT;

-- Verificar estado final
SELECT 'ESTADO FINAL - CARRITOS:' as info;
SELECT ID_CARRITO, FECHA_CREACION FROM CARRITOS ORDER BY ID_CARRITO;

SELECT 'ESTADO FINAL - PRODUCTOS EN CARRITOS:' as info;
SELECT ID_CARRITO, COUNT(*) as productos FROM CARRITO_PRODUCTOS GROUP BY ID_CARRITO ORDER BY ID_CARRITO; 